"""Adversarial generator: a grammar over store operations, an oracle, and a comparison.

``nemisis redteam`` renders handler modules from a small grammar (guard, credit, mark, the atomic
call, a raw write beside the database, a raw SQL write through a private connection, in any
order), runs ``check`` on each, and compares the verdict with an oracle computed from the
operation sequence alone. The oracle knows what each store call does to the durable state and
where a kill can land (only at store commits); it never runs code. Any disagreement is either a
checker false pass or false fail (the most valuable bug this repository can find) or an oracle
bug, and either way it is a failure of this command.

This module is not a trusted engine resource: it writes candidates and reads verdicts, it never
judges.
"""

from __future__ import annotations

import os
import random
from collections.abc import Sequence
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from nemisis.crash_fixture import BUGGY_REF, SCENARIO_ID
from nemisis.crash_models import CrashVerdict
from nemisis.crashcheck import check

AMOUNT = 2500


class Op(StrEnum):
    """One statement of a generated handler, in the credit scenario's vocabulary."""

    GUARD = "guard"  # if store.processed(event_id): return
    CREDIT = "credit"  # store.credit(...)                     one commit
    MARK = "mark"  # store.mark_processed(...)             one commit
    ATOMIC = "atomic"  # store.credit_and_mark(...)            one commit, no-op once marked
    RAW_FILE = "raw_file"  # open("side.txt", "a").write(...)   durable write beside the database
    RAW_SQL = "raw_sql"  # sqlite3 credit through store._database, no store commit


_RENDER = {
    Op.GUARD: '    if store.processed(event["event_id"]):\n        return\n',
    Op.CREDIT: '    store.credit(event["account_id"], event["event_id"], event["amount_cents"])\n',
    Op.MARK: '    store.mark_processed(event["event_id"])\n',
    Op.ATOMIC: (
        '    store.credit_and_mark(event["account_id"], event["event_id"], event["amount_cents"])\n'
    ),
    Op.RAW_FILE: (
        '    with open("side.txt", "a", encoding="utf-8") as side:\n        side.write("x\\n")\n'
    ),
    Op.RAW_SQL: (
        "    with sqlite3.connect(store._database, isolation_level=None) as connection:\n"
        '        connection.execute("BEGIN IMMEDIATE")\n'
        "        connection.execute(\n"
        '            "UPDATE accounts SET balance_cents = balance_cents + ? "\n'
        '            "WHERE account_id = ?",\n'
        '            (event["amount_cents"], event["account_id"]),\n'
        "        )\n"
        "        connection.execute(\n"
        '            "INSERT INTO credit_ledger(event_id, account_id, amount_cents) "\n'
        '            "VALUES (?, ?, ?)",\n'
        '            (event["event_id"], event["account_id"], event["amount_cents"]),\n'
        "        )\n"
        "        connection.commit()\n"
    ),
}


def render(ops: Sequence[Op]) -> str:
    """The handler module for one operation sequence."""
    header = '"""Generated by nemisis redteam; the ops are the whole story."""\n\n'
    if Op.RAW_SQL in ops:
        header += "import sqlite3\n\n\n"
    else:
        header += "\n"
    body = "".join(_RENDER[op] for op in ops) or "    return\n"
    return f"{header}def apply_credit(store, event):\n{body}"


class Expected(StrEnum):
    PROVEN = CrashVerdict.FIX_PROVEN_FOR_THIS_CAPSULE.value
    STILL_REPRODUCES = CrashVerdict.PATCH_FAILED_STILL_REPRODUCES.value
    INVARIANT_BROKEN = CrashVerdict.PATCH_FAILED_INVARIANT_BROKEN.value
    INCOMPLETE = CrashVerdict.EVIDENCE_INCOMPLETE.value


@dataclass
class _World:
    """Durable state for one event, as the probe sees it, plus the raw writes that hid from it."""

    balance: int = 0
    ledger: int = 0
    marker: int = 0
    side_file: bool = False
    raw_sql: bool = False

    def state(self) -> tuple[int, int, int]:
        return (self.balance, self.ledger, self.marker)


class _Stop(Exception):
    """The delivery ended: by returning, by raising, or by the kill."""

    def __init__(self, kind: str) -> None:
        super().__init__(kind)
        self.kind = kind


def _deliver(world: _World, ops: Sequence[Op], *, kill_after_commit: int | None) -> str:
    """Run one delivery on the world. Returns 'done', 'error', or 'killed'.

    A commit is a kill point; the k-th commit ends the delivery when ``kill_after_commit == k``.
    A second marker for the same event raises (PRIMARY KEY), which the real worker reports as an
    error. ``credit_and_mark`` after a marker is a silent no-op with no commit.
    """
    commits = 0

    def commit() -> None:
        nonlocal commits
        commits += 1
        if kill_after_commit is not None and commits == kill_after_commit:
            raise _Stop("killed")

    try:
        for op in ops:
            if op is Op.GUARD:
                if world.marker:
                    return "done"
            elif op is Op.CREDIT:
                world.balance += AMOUNT
                world.ledger += 1
                commit()
            elif op is Op.MARK:
                if world.marker:
                    return "error"
                world.marker = 1
                commit()
            elif op is Op.ATOMIC:
                if world.marker:
                    continue
                world.balance += AMOUNT
                world.ledger += 1
                world.marker = 1
                commit()
            elif op is Op.RAW_FILE:
                world.side_file = True
            elif op is Op.RAW_SQL:
                world.balance += AMOUNT
                world.ledger += 1
                world.raw_sql = True
    except _Stop as stop:
        return stop.kind
    return "done"


def _commit_count(ops: Sequence[Op]) -> int:
    world = _World()
    count = 0
    for op in ops:
        if op is Op.GUARD and world.marker:
            break
        if op is Op.CREDIT:
            world.balance += AMOUNT
            world.ledger += 1
            count += 1
        elif op is Op.MARK:
            if world.marker:
                break
            world.marker = 1
            count += 1
        elif op is Op.ATOMIC:
            if not world.marker:
                world.balance += AMOUNT
                world.ledger += 1
                world.marker = 1
                count += 1
        elif op is Op.RAW_SQL:
            world.balance += AMOUNT
            world.ledger += 1
    return count


def _classify(world: _World) -> str:
    if (world.balance, world.ledger) == (2 * AMOUNT, 2):
        return "DUPLICATE_EFFECT"
    if world.state() == (AMOUNT, 1, 1):
        return "EXACTLY_ONCE"
    return "INVARIANT_FAILED"


def _boundary_commit(ops: Sequence[Op]) -> int | None:
    """The first store commit at which the effect is durable (balance 2500, one ledger row)."""
    world = _World()
    commits = 0
    for op in ops:
        if op is Op.GUARD and world.marker:
            return None
        if op is Op.CREDIT:
            world.balance += AMOUNT
            world.ledger += 1
            commits += 1
        elif op is Op.MARK:
            if world.marker:
                return None
            world.marker = 1
            commits += 1
        elif op is Op.ATOMIC:
            if world.marker:
                continue
            world.balance += AMOUNT
            world.ledger += 1
            world.marker = 1
            commits += 1
        elif op is Op.RAW_SQL:
            world.balance += AMOUNT
            world.ledger += 1
            continue
        else:
            continue
        if (world.balance, world.ledger) == (AMOUNT, 1):
            return commits
    return None


def _raw(world: _World) -> bool:
    return world.side_file or world.raw_sql


def oracle(ops: Sequence[Op]) -> tuple[Expected, str]:
    """What the checker must say about this operation sequence, from the sequence alone.

    The simulation runs exactly the worlds the engine runs, in the engine's order: five boundary
    worlds (kill at the effect commit, redeliver), then, only if those end exactly once, a census
    (two deliveries, no kill) and one sweep world per commit of the first delivery. A raw write
    forfeits the verdict only in a world that actually executes it; dead code after a guard is
    not a write. A world whose redelivery raises is incomplete, and one incomplete sweep world
    makes the sweep incomplete unless the census already decided.
    """
    boundary = _boundary_commit(ops)
    if boundary is None:
        world = _World()
        _deliver(world, ops, kill_after_commit=None)
        if _raw(world):
            return Expected.INCOMPLETE, "a write around the store forfeits the verdict"
        return Expected.INCOMPLETE, "the durable credit checkpoint is never reached on a fresh seed"
    world = _World()
    assert _deliver(world, ops, kill_after_commit=boundary) == "killed"
    redelivery = _deliver(world, ops, kill_after_commit=None)
    if _raw(world):
        return Expected.INCOMPLETE, "a write around the store forfeits the verdict"
    if redelivery != "done":
        return Expected.INCOMPLETE, "the redelivery after the boundary kill raised"
    observation = _classify(world)
    if observation == "DUPLICATE_EFFECT":
        return Expected.STILL_REPRODUCES, "the boundary worlds duplicate"
    if observation == "INVARIANT_FAILED":
        return Expected.INVARIANT_BROKEN, "the boundary worlds break the invariant"
    # Census: two deliveries, no kill; one delivery must already be exactly once.
    census = _World()
    first_run = _deliver(census, ops, kill_after_commit=None)
    if _raw(census):
        return Expected.INCOMPLETE, "a write around the store forfeits the verdict"
    if first_run != "done":
        return Expected.INCOMPLETE, "the first no-kill delivery raised"
    first = _classify(census)
    second_run = _deliver(census, ops, kill_after_commit=None)
    if _raw(census):
        return Expected.INCOMPLETE, "a write around the store forfeits the verdict"
    if second_run != "done":
        return Expected.INCOMPLETE, "the no-kill redelivery raised"
    final = _classify(census)
    if final == "DUPLICATE_EFFECT":
        return Expected.STILL_REPRODUCES, "the no-kill census duplicates"
    if final == "INVARIANT_FAILED" or first != "EXACTLY_ONCE":
        return Expected.INVARIANT_BROKEN, "the no-kill census is wrong before any crash"
    # Sweep: kill once after each commit of the first delivery, then redeliver; every world must
    # complete before any kill point may decide.
    seen: list[str] = []
    for point in range(1, _commit_count(ops) + 1):
        world = _World()
        if _deliver(world, ops, kill_after_commit=point) != "killed":
            return Expected.INCOMPLETE, f"the sweep could not reach commit {point}"
        outcome = _deliver(world, ops, kill_after_commit=None)
        if _raw(world):
            return Expected.INCOMPLETE, "a write around the store forfeits the verdict"
        if outcome != "done":
            return Expected.INCOMPLETE, f"the redelivery after commit {point} raised"
        seen.append(_classify(world))
    if "DUPLICATE_EFFECT" in seen:
        return Expected.STILL_REPRODUCES, "a sweep kill point duplicates"
    if "INVARIANT_FAILED" in seen:
        return Expected.INVARIANT_BROKEN, "a sweep kill point breaks the invariant"
    return Expected.PROVEN, "every kill point ends exactly once"


def generate(cases: int, seed: int) -> list[tuple[Op, ...]]:
    """Distinct operation sequences from a fixed seed; the same seed always yields the same list."""
    rng = random.Random(seed)
    alphabet = list(Op)
    weights = [3, 5, 3, 5, 1, 1]
    seen: set[tuple[Op, ...]] = set()
    out: list[tuple[Op, ...]] = []
    attempts = 0
    while len(out) < cases and attempts < cases * 200:
        attempts += 1
        length = rng.choice([1, 2, 2, 3, 3, 4])
        ops = tuple(rng.choices(alphabet, weights=weights, k=length))
        if ops in seen:
            continue
        seen.add(ops)
        out.append(ops)
    return out


@dataclass(frozen=True)
class Case:
    index: int
    ops: tuple[Op, ...]
    expected: Expected
    reason: str
    verdict: str
    summary: str

    @property
    def agrees(self) -> bool:
        return self.verdict == self.expected.value


def run(cases: int, seed: int, out: Path) -> list[Case]:
    """Render, run, and compare every generated case; artifacts land under ``out``."""
    results: list[Case] = []
    # CrashCheck refuses symlinked evidence parents (macOS's /tmp -> /private/tmp); resolve first.
    out = out.resolve()
    previous = os.environ.get("NEMISIS_ARTIFACT_ROOT")
    for index, ops in enumerate(generate(cases, seed), start=1):
        expected, reason = oracle(ops)
        tree = out / f"case-{index:03d}"
        (tree / "app").mkdir(parents=True, exist_ok=False)
        (tree / "app" / "__init__.py").write_text('"""generated"""\n', encoding="utf-8")
        (tree / "app" / "credits.py").write_text(render(ops), encoding="utf-8")
        os.environ["NEMISIS_ARTIFACT_ROOT"] = str(out / f"artifacts-{index:03d}")
        try:
            result = check(BUGGY_REF, tree, SCENARIO_ID, mode="local")
            verdict, summary = result.verdict.value, result.summary
        except Exception as error:  # a crash of the checker is itself a disagreement
            verdict, summary = f"ERROR:{type(error).__name__}", str(error)[:500]
        finally:
            if previous is None:
                os.environ.pop("NEMISIS_ARTIFACT_ROOT", None)
            else:
                os.environ["NEMISIS_ARTIFACT_ROOT"] = previous
        results.append(Case(index, ops, expected, reason, verdict, summary))
    return results


__all__ = ["Case", "Expected", "Op", "generate", "oracle", "render", "run"]
