"""The adversarial generator: the oracle knows the zoo, and the checker agrees with it."""

from __future__ import annotations

from pathlib import Path

import pytest

from nemisis.redteam import Expected, Op, generate, oracle, render, run

G, C, M, A, F, S = Op.GUARD, Op.CREDIT, Op.MARK, Op.ATOMIC, Op.RAW_FILE, Op.RAW_SQL


@pytest.mark.parametrize(
    ("ops", "expected", "reason"),
    [
        # The packaged zoo, as operation sequences.
        ((G, C, M), Expected.STILL_REPRODUCES, "boundary"),  # buggy / misleading-green
        ((A,), Expected.PROVEN, "every kill point"),  # atomic
        ((G, M, C), Expected.INVARIANT_BROKEN, "sweep"),  # mark-first
        ((A, C), Expected.STILL_REPRODUCES, "boundary"),  # leftover-credit
        ((C,), Expected.STILL_REPRODUCES, "boundary"),  # never-marks
        ((S,), Expected.INCOMPLETE, "around the store"),  # raw-sql
        # Shapes from the hardening night.
        ((G, A, C), Expected.STILL_REPRODUCES, "census"),  # guarded leftover credit
        ((C, C, M), Expected.INVARIANT_BROKEN, "boundary"),  # over-crediting
        ((M, A), Expected.INCOMPLETE, "never reached"),  # mark then atomic
        ((M,), Expected.INCOMPLETE, "never reached"),
        ((G,), Expected.INCOMPLETE, "never reached"),
        ((S, M), Expected.INCOMPLETE, "around the store"),  # raw credit, store marker
        ((A, S), Expected.INCOMPLETE, "around the store"),  # drift after the last commit
        ((F, A), Expected.INCOMPLETE, "around the store"),  # inflight file
        ((C, M, M), Expected.INCOMPLETE, "raised"),  # a second marker raises on redelivery
        ((M, C), Expected.INCOMPLETE, "raised"),  # unguarded mark-first raises on redelivery
        ((A, A), Expected.PROVEN, "every kill point"),
        ((G, M, C, C), Expected.STILL_REPRODUCES, "census"),
        # Reachability: a raw write is only a write if some world executes it. Case 44 of the
        # first 60-case sweep: the checker was right and the oracle was wrong.
        ((A, G, S, C), Expected.PROVEN, "every kill point"),
        ((A, G, F), Expected.PROVEN, "every kill point"),
        ((G, A, F), Expected.INCOMPLETE, "around the store"),
        ((C, G, S, M), Expected.INCOMPLETE, "around the store"),
        ((G, C, M, F), Expected.INCOMPLETE, "around the store"),
    ],
)
def test_oracle_knows_the_zoo(ops: tuple[Op, ...], expected: Expected, reason: str) -> None:
    verdict, why = oracle(ops)
    assert verdict is expected, why
    assert reason in why


def test_generation_is_deterministic_and_distinct() -> None:
    first = generate(40, seed=7)
    assert first == generate(40, seed=7)
    assert len(first) == 40 == len(set(first))
    assert generate(40, seed=8) != first
    assert all(1 <= len(ops) <= 4 for ops in first)


def test_render_is_a_bindable_handler() -> None:
    source = render((G, S, M))
    assert source.startswith('"""Generated by nemisis redteam')
    assert "import sqlite3" in source
    assert "def apply_credit(store, event):" in source
    assert "store._database" in source
    assert render(()).endswith("    return\n")


def test_ten_generated_handlers_agree_with_the_oracle(tmp_path: Path) -> None:
    """The normal-suite sweep: fixed seed, bounded runtime, zero disagreements."""
    cases = run(10, seed=7, out=tmp_path / "redteam")

    assert len(cases) == 10
    disagreements = [case for case in cases if not case.agrees]
    assert not disagreements, [
        (case.index, case.ops, case.expected, case.verdict, case.summary) for case in disagreements
    ]
    assert {case.expected for case in cases} >= {Expected.INCOMPLETE}
